### ISSUE TITLE
Question about max distance between start->goal in 7x7 setting

### ISSUE THREAD

**Issue by BoopSainy** [aleksispi/airloc#1]
Hi!

Congratulations to see your paper is accepted in ICLR! 

I am really interested in your work and I have a few questions about the configurations.

1. Could I know the max distance between starting patch to goal patch in 7x7 setting? I notice it is set to 8 in 5x5 setting but I guess it might be different in 7x7 setting.
2. Is the "decision unit" implemented explicitly or actually included in "LSTM temporal unit"? I read the code and I notice you build up the "decision unit (policy network)" in rl_agent.py, but seems like this network isn't be implemented as "policy network". 

Really thanks for your work and help!

**Comment by aleksispi** [comment]
Hi!

Thank you very much, and I'm happy to hear that you find this work interesting! :)

1. Thank you for pointing me to this. I will add a clarifying comment for the flag `CONFIG.RL_max_start_goal_dist = 8` in `config.py`, to explain that the actual max-start-goal-distance is min(grid_size-1, CONFIG.RL_max_start_goal_dist) in the default setting (grid-like setup, see the flag `CONFIG.MISC_grid_game = True`). Thus, as it is now, the actual max-start-goal-distance will be 4 for 5x5, and 6 for 7x7. (Note that a goal can be max 4 steps away from start in 5x5, and at most 6 steps away in 7x7.) To see that this is the case, see the file `utils.py` in the folder `utils`, and in particular see around Line 197-199 there. When I update the config so that it has this comment, I will also increase `CONFIG.RL_max_start_goal_dist` to a very large value, so that if one would attempt even larger setups, the max distance can be larger than 8.
2. To the best of my understanding, the decision unit is specified around Line 91-93 in `rnn_agents.py` in the folder `networks`.

**Comment by BoopSainy** [comment]
Hi,

Really thanks for your answers! These help me a lot!

I have another quick question: after evaluation on well-trained model, which _.npz_ file could reflect the **Success**? 

Thanks!

**Comment by aleksispi** [comment]
Hi,

No worries, glad to be able to help! I think both 'HasConverged.npz' and 'IoU.npz' represent success rate (in the range [0,1]). This is at least true in the grid-like setup that is default. Also note that there should be some similar .npz-files which show the success versus starting distance to goal. For example 'SeparatedHasConverged.npz'.

Cheers

**Comment by BoopSainy** [comment]
Hi,

Really thanks for your help! Let me check more details from you awesome codes!

Thanks
